export const EMAIL_TEMPLATE_TYPE_IDS = [
  'abandoned_cart_email',
  'giftcertificate_email',
  'createaccount_email',
  'createguestaccount_email',
  'account_details_changed_email',
  'account_reset_password_email',
  'passwordless_login_email',
  'ordermessage_notification',
  'invoice_email',
  'combined_order_status_email',
  'return_confirmation_email',
  'return_statuschange_email',
  'product_review_email',
  'order_ready_for_pickup',
]
